#devModes:
#  oidcSmartIntrospect:
#    enabled: true
#    fakeUid:
#      subject: subject
#      issuer: issuer
#      email: a@mail.it
#      emailVerified: true
#      token: header.body.signature
#      roles:
#        - admin
#      allRoles:
#        - ids:admin
#      audience: ids
#      expires: 3600
#      issuedAt: -1
#      active: true
oidc:
  issuers:
  - issuer: https://id.ecobonus.es/auth/realms/dev-gestori
    introspection_endpoint: https://id.ecobonus.es/auth/realms/dev-gestori/protocol/openid-connect/token/introspect
    client:
      client_id: ids-api
      client_secret: 1e1c513f-1ccb-4c7e-bf12-827948f44f6f
  - issuer: https://id.ecobonus.es/auth/realms/dev-operatori
    introspection_endpoint: https://id.ecobonus.es/auth/realms/dev-operatori/protocol/openid-connect/token/introspect
    client:
      client_id: ids-api
      client_secret: d108fed9-8b4a-434a-830f-77b201e06150
# https://github.com/expressjs/cookie-session
cookie:
  name: nightswatch
  keys:
    - you_know_nothing_jon_snow
  maxAge: 86400 #24h
targets:
  path: /**
  upstream: http://httpbin.org
  routes: []
  #  - path: /_dev
  #    upstream: http://httpbin.org
  rewrite: []
  #  - match: ^/_dev
  #    rewrite: '/headers'

storage:
  kind: InMemory
  specs:
    stdTTL: 86400 #24h
server:
  # max_body_limit: 100k
  http:
    enable: true
    port: 3000
  # to be implemented
  https:
    enable: false
    port: 3001
  max_header_size: 8192
  proxy:
    # http://expressjs.com/en/guide/behind-proxies.html
    # loopback - 127.0.0.1/8, ::1/128
    # linklocal - 169.254.0.0/16, fe80::/10
    # uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
    - loopback
    - linklocal
    - uniquelocal
  healthchecks:
    readiness: /healthcheck/ready
    liveness: /healthcheck
    timeout: 2000 #2sec
relying_party:
  on_success_redirect: /
  on_fail_redirect: /
  oidc_base_path: /oidc
  oidc_paths:
    login: /login
    callback: /callback
  rules:
    - route: /**
      methods:
        - all
  logLevel: error
  headers:
    prefix: X-AUTH
    proxy:
      access-token: tokenset.access_token
      id-token: tokenset.id_token
      expires-at: tokenset.expires_at
      expires-in: tokenset.expires_in
      sub: idtoken.sub
      name: idtoken.name
      email: idtoken.email
      family-name: idtoken.family_name
      given-name: idtoken.given_name
