version: '3.6'
services:
  nightswatch:
    build:
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspace:cached
      - node_modules:/workspace/node_modules:cached
      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode-ext:/root/.vscode-server/extensions
      # And/or for VS Code Insiders
      - vscode-ext-insiders:/root/.vscode-server-insiders/extensions
      - ${HOME}${USERPROFILE}/.npmrc:/root/.npmrc:ro
      - ${HOME}${USERPROFILE}/.gitconfig:/root/.gitconfig:ro
      - ${HOME}${USERPROFILE}/.ssh:/root/.ssh:ro
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


    # Uncomment the next four lines if you will use a ptrace-based debuggers like C++, Go, and Rust.
    # cap_add:
    #  - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  node_modules:
  vscode-ext:
  vscode-ext-insiders:
