oidc:
  # issuerUri: process.env.OIDC__ISSUERURI,
  # client_id: process.env.OIDC__CLIENTID,
  # client_secret: process.env.OIDC__CLIENT_SECRET,
  # redirect_uri: process.env.OIDC__REDIRECT_URI,
  scopes: openid profile email offline_access

# https://github.com/expressjs/cookie-session
cookie:
  name: nightswatch,
  keys:
    - a_reandom_secret
  maxAge: 24h
targets:
  default:
    # mount: /**
    upstream: http://httpbin.com
storage:
  kind: InMemory
  specs:
    stdTTL: 24h
server:
  max_body_limit: 100k
  port: 3000
  max_header_size: 8192
  proxy:
  # http://expressjs.com/en/guide/behind-proxies.html
  # loopback - 127.0.0.1/8, ::1/128
  # linklocal - 169.254.0.0/16, fe80::/10
  # uniquelocal - 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16, fc00::/7
    - loopback
    - linklocal
    - uniquelocal
  healthchecks:
    readiness: /healthcheck/ready
    liveness:  /healthcheck
    timeout: 2s
relying_party:
  on_success_redirect: /
  on_fail_redirect: /
  oidc_base_path: /oidc
  oidc_paths:
    login: /login
    callback: /callback
  headers:
    prefix: X-AUTH
    proxy:
      access-token: tokenset.access_token
      id-token: tokenset.id_token
      expires-at: tokenset.expires_at
      expires-in: tokenset.expires_in
      sub: profile.sub
      name: profile.name
      email: profile.email
      roles: profile.roles
      family-name: profile.family_name
      given-name: profile.given_name
